[workspace]
resolver = "2"
members = [
  "hui",
  "hui-derive",
  "hui-examples",
  "hui-glium",
  "hui-painter",
  "hui-shared",
  "hui-wgpu",
  "hui-winit",
  "hui-loaders",
  "bevy_hui",
  "hui-euc",
]
